services:

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=later
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=later
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge